// Shared StyleSheet for the SchoolSync mobile app. Extracted from the
// original single-file app/index.tsx so every screen/component draws from
// one place instead of redefining the same card/list/pill styles.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  header: { paddingHorizontal: 20, paddingVertical: 22 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  logo: { width: 52, height: 52, borderRadius: 12, backgroundColor: '#fff' },
  logoFallback: { width: 52, height: 52, borderRadius: 12, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  logoText: { color: '#1976D2', fontWeight: '800', fontSize: 24 },
  brandText: { flex: 1 },
  title: { fontSize: 26, fontWeight: '700', color: '#fff' },
  subtitle: { fontSize: 14, color: '#E3F2FD', marginTop: 6 },
  poweredBy: { fontSize: 12, color: '#E3F2FD', marginTop: 4 },
  headerActions: { flexDirection: 'row', gap: 10, alignItems: 'center', marginTop: 12 },
  rolePill: { overflow: 'hidden', borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.18)', color: '#fff', paddingHorizontal: 10, paddingVertical: 5, fontSize: 12, fontWeight: '700' },
  card: { backgroundColor: '#fff', borderRadius: 14, marginHorizontal: 14, marginTop: 14, padding: 14, borderWidth: 1, borderColor: '#e8e8e8' },
  lastCard: { marginBottom: 24 },
  attendanceCard: { gap: 12 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#222', marginBottom: 10 },
  label: { fontSize: 14, fontWeight: '600', color: '#222', marginBottom: 6 },
  input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 15, color: '#222', marginBottom: 12, backgroundColor: '#fff' },
  segmented: { flexDirection: 'row', borderWidth: 1, borderColor: '#dbe2ea', borderRadius: 12, padding: 3, marginBottom: 14, backgroundColor: '#f8fafc' },
  segment: { flex: 1, borderRadius: 9, paddingVertical: 9, alignItems: 'center' },
  segmentText: { fontSize: 13, color: '#475569', fontWeight: '700' },
  segmentTextActive: { color: '#fff' },
  primaryButton: { borderRadius: 10, paddingVertical: 12, alignItems: 'center', marginTop: 4 },
  primaryButtonDisabled: { backgroundColor: '#9bb8d8' },
  primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  errorText: { color: '#d32f2f', marginBottom: 10, fontSize: 13 },
  errorBanner: { backgroundColor: '#ffebee', color: '#b71c1c', marginHorizontal: 14, marginTop: 14, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 13 },
  inlineError: { backgroundColor: '#fff1f2', borderWidth: 1, borderColor: '#fecdd3', marginHorizontal: 14, marginTop: 14, borderRadius: 12, padding: 12 },
  inlineErrorTitle: { color: '#9f1239', fontSize: 14, fontWeight: '800' },
  inlineErrorText: { color: '#be123c', fontSize: 12, lineHeight: 17, marginTop: 4 },
  infoBox: { backgroundColor: '#eef6ff', color: '#1d4f8f', padding: 10, borderRadius: 10, fontSize: 12, lineHeight: 17, marginBottom: 12 },
  logoutButton: { backgroundColor: 'rgba(0,0,0,0.18)', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6 },
  logoutButtonText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  pilotBadge: { backgroundColor: '#f59e0b', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  pilotBadgeText: { color: '#1f2937', fontWeight: '800', fontSize: 10, letterSpacing: 0.5 },
  childChip: { borderWidth: 1, borderColor: '#dbe8f6', backgroundColor: '#f8fbff', borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, marginRight: 10, minWidth: 150 },
  childChipText: { fontSize: 15, fontWeight: '700', color: '#1f2937' },
  childChipSubtext: { marginTop: 4, fontSize: 12, color: '#596779' },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, gap: 8 },
  summaryText: { fontSize: 13, fontWeight: '600', color: '#333' },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  listRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  listRowLeft: { flexShrink: 1, paddingRight: 10 },
  listRowTitle: { fontSize: 14, fontWeight: '600', color: '#222' },
  listRowSubtext: { marginTop: 2, fontSize: 12, color: '#666' },
  listRowValue: { fontSize: 13, fontWeight: '600', color: '#1976D2', textAlign: 'right' },
  feeAction: { alignItems: 'flex-end', gap: 6 },
  homeworkRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  homeworkMeta: { alignItems: 'flex-end', gap: 6 },
  statusPill: { overflow: 'hidden', borderRadius: 999, backgroundColor: '#e9f2ff', color: '#0d47a1', paddingHorizontal: 8, paddingVertical: 3, fontSize: 10, fontWeight: '700' },
  methodPill: { overflow: 'hidden', borderRadius: 999, backgroundColor: '#f3f4f6', color: '#374151', paddingHorizontal: 8, paddingVertical: 3, fontSize: 10, fontWeight: '700' },
  statusBadge: { overflow: 'hidden', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, fontSize: 12, fontWeight: '800' },
  statusBadgeSuccess: { backgroundColor: '#dcfce7', color: '#166534' },
  statusBadgeMuted: { backgroundColor: '#f1f5f9', color: '#475569' },
  remarkText: { marginTop: 5, fontSize: 12, lineHeight: 16, color: '#4b5563' },
  submitWrap: { marginTop: 10, flexDirection: 'row', gap: 8, alignItems: 'center' },
  submitInput: { flex: 1, borderWidth: 1, borderColor: '#ddd', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 13, color: '#222', backgroundColor: '#fff' },
  smallButton: { backgroundColor: '#1976D2', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  smallButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  announcementCard: { borderWidth: 1, borderColor: '#ededed', borderRadius: 10, padding: 10, marginBottom: 10, backgroundColor: '#fcfcfc' },
  announcementTitle: { fontSize: 15, fontWeight: '700', color: '#222' },
  announcementBody: { marginTop: 6, fontSize: 13, lineHeight: 18, color: '#444' },
  announcementMeta: { marginTop: 8, fontSize: 12, color: '#666' },
  emptyText: { color: '#666', fontSize: 13, lineHeight: 19 },
  loaderWrap: { paddingVertical: 40 },
  teacherHero: { marginHorizontal: 14, marginTop: 14, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: '#e2e8f0', backgroundColor: '#ffffff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  teacherHeroText: { flex: 1 },
  teacherHeroLabel: { color: '#64748b', fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  teacherHeroTitle: { color: '#0f172a', fontSize: 20, fontWeight: '800', marginTop: 3 },
  teacherHeroSubtext: { color: '#475569', fontSize: 12, lineHeight: 17, marginTop: 5 },
  teacherListItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  teacherListBody: { flex: 1 },
  teacherMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  periodBadge: { minWidth: 38, borderRadius: 10, borderWidth: 1, paddingVertical: 7, paddingHorizontal: 8, alignItems: 'center', backgroundColor: '#f8fafc' },
  periodBadgeText: { fontSize: 12, fontWeight: '800' },
  studentProfileCard: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  studentAvatar: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  studentAvatarText: { color: '#fff', fontSize: 24, fontWeight: '800' },
  studentProfileBody: { flex: 1 },
  studentName: { fontSize: 18, fontWeight: '800', color: '#0f172a' },
  studentClassLine: { marginTop: 3, fontSize: 13, fontWeight: '600', color: '#475569' },
  studentMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  studentMetaPill: { overflow: 'hidden', borderRadius: 999, backgroundColor: '#eef2ff', color: '#3730a3', paddingHorizontal: 9, paddingVertical: 3, fontSize: 11, fontWeight: '700' },
  studentSchool: { marginTop: 8, fontSize: 12, color: '#64748b', fontWeight: '600' },
  attendancePct: { fontSize: 20, fontWeight: '800', marginBottom: 10 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 },
  overviewTile: { width: '47%', borderWidth: 1, borderColor: '#eef0f3', borderRadius: 12, padding: 12, backgroundColor: '#fbfcfe' },
  overviewNumber: { fontSize: 24, fontWeight: '800' },
  overviewLabel: { color: '#475569', fontSize: 12, marginTop: 4, fontWeight: '600' },

  // Simple back-arrow sub-screen header, shared by every Student Portal
  // detail screen (Profile/Timetable/Attendance/Marks/Report Cards/
  // Announcements) and the portal Search screen — distinct from
  // components/BrandHeader.tsx's ActorHeader, which is branding-first and
  // has no back navigation.
  subScreenHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 18, gap: 14 },
  subScreenHeaderTitle: { flex: 1, fontSize: 20, fontWeight: '700', color: '#fff' },
  subScreenHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 14 },

  // Student Portal grid (3-column icon-tile menu).
  portalGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 10, paddingTop: 16, gap: '2%' },
  portalTile: { width: '31.33%', alignItems: 'center', backgroundColor: '#f5f7fa', borderRadius: 16, paddingVertical: 16, paddingHorizontal: 6, marginBottom: 14 },
  portalTileBadge: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  portalTileLabel: { fontSize: 12, fontWeight: '600', color: '#1f2937', textAlign: 'center', lineHeight: 16 },

  // Student Portal search (filterable vertical list, same tiles as rows).
  searchInputWrap: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8 },
  searchInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: '#dbe2ea', borderRadius: 999, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#fff' },
  searchInput: { flex: 1, fontSize: 15, color: '#222', padding: 0 },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 16, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  searchRowBadge: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  searchRowLabel: { fontSize: 15, fontWeight: '600', color: '#222' },
});
